---
title: "Plum Book App"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: united
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(DT)
library(plotly)

plum_combined <- readRDS("processed_data/plum_combined.rds")

#factorize categorical columns to help with DT table filtering
glimpse(plum_combined)

plum_combined <- plum_combined %>% 
  mutate(
    agcy_name = as.factor(agcy_name),
    org_name = as.factor(org_name),
    tenure = as.factor(tenure),
    type_of_appt = as.factor(type_of_appt),
    type_of_appt_full = as.factor(type_of_appt_full),
    pay_plan = as.factor(pay_plan),
    pay_plan_full = as.factor(pay_plan_full)
  )



```

Searchable Database
===================================== 

Column 
-----------------------------------------------------------------------

### 
To filter, click on the boxes above the columns. To sort, use the up/down arrows by the column names.

```{r}

plum_combined_selectcols <- plum_combined %>% 
  select(
    -org_name_level,
    -id_number,
    -pay_plan,
    -type_of_appt
  ) %>% 
  arrange(agcy_name)

datatable(plum_combined_selectcols,
          rownames = FALSE,
          filter = "top",
          extensions = 'Buttons',
          options = list(searchHighlight = TRUE, pageLength = 15, dom = 'Bfrtip',
                    buttons = c('copy', 'csv', 'excel', 'print')
                    )) %>%
          formatDate("expires")
          
```

Summary Charts
===================================== 

Column 
-----------------------------------------------------------------------

### Top Departments (# of Positions)

```{r}

byagency <- plum_combined %>%
  count(agcy_name) %>%
  arrange(desc(n)) %>% 
  head(15)

#reorder factors to order bars descending
byagency <- byagency %>%
  mutate(
    agcy_name = str_remove(agcy_name, "DEPARTMENT OF THE "),
    agcy_name = str_remove(agcy_name, "DEPARTMENT OF "),
    agcy_name = as.factor(agcy_name),
    agcy_name = fct_reorder(agcy_name, n)
    )

#make chart
d <- ggplot(data = byagency, aes(x = agcy_name, y = n)) +
  geom_col(
    # color = "#848484",
    fill = "#ffb3ba") + 
  coord_flip() +
  theme_minimal()
d2 <- d + labs(x ="", y = "") +
  theme(legend.title=element_blank()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
dd <- ggplotly(d2) 
dd_nomenu <- dd %>% config(displayModeBar = FALSE)
dd_nomenu



```

Column 
-----------------------------------------------------------------------

### Appointment Types (# of Positions)

```{r}


bytype <- plum_combined %>%
  filter(type_of_appt_full != "none included") %>% 
  count(type_of_appt_full) %>%
  arrange(desc(n))

#reorder factors to order bars descending
bytype <- bytype %>%
  mutate(
    type_of_appt_full = as.factor(type_of_appt_full),
    type_of_appt_full = fct_reorder(type_of_appt_full, n)
    )

#make chart
d <- ggplot(data = bytype, aes(x = type_of_appt_full, y = n)) +
  geom_col(
    # color = "#848484",
    fill = "#BEE5A3") + 
  coord_flip() +
  theme_minimal()
d2 <- d + labs(x ="", y = "") +
  theme(legend.title=element_blank()) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
dd <- ggplotly(d2) 
dd_nomenu <- dd %>% config(displayModeBar = FALSE)
dd_nomenu


```

